routes/web.php
<?php

Auth::routes();


Route::get('/', 'HomeController@commande')->name('dashboard');

Route::get('/dashboard', 'HomeController@commande')->name('dashboard.display');


Route::resource('users', 'UserController');

Route::match(['put', 'patch'],'users/changePass/{user}', 'UserController@updatePass')->name('users.updatePass');
Route::match(['put', 'patch'],'users/changeLogo/{user}', 'UserController@updateLogo')->name('users.updateLogo');


Route::resource('roles', 'RoleController');

Route::resource('permissions', 'PermissionController');

Route::resource('posts', 'PostController');

Route::resource('articles', 'ArticleController');


Route::get('/commandes/{nombre_semaine?}/{nombre_anne?}', 'CommandesController@semaine')->name('commandes');
Route::get('/commandes-historique/{nombre_semaine?}', 'CommandesController@historiqueSemaine')->name('historique.commandes');
Route::post('/commande/create', 'CommandesController@store')->name('commande.create');
Route::post('/commande/create2', 'CommandesController@store2')->name('commande.create2');

Route::get('/previsions/{anne?}/{nombre_mois?}', 'PrevisionsController@mois')->name('previsions');
Route::post('/previsions/create', 'PrevisionsController@store')->name('previsions.create');

Route::get('/previsions_hebdo/{anne?}/{nombre_mois?}', 'PrevisionsController@mois2')->name('previsions_hebdo');
Route::post('/previsions/create2', 'PrevisionsController@store2')->name('previsions.create2');

Route::post('/previsions/save_repartition', 'PrevisionsController@saveRepartition')->name('repartition.save');

/*** For ERP **/
Route::get('/getcommandes/{last_update}', 'ErpController@getCommandes')->name('erp.commandes');
Route::get('/getprevisions/{last_update}', 'ErpController@getPrevisions')->name('erp.previsions');

Route::get('/historique-log/{id_user?}', 'LogsController@getHistorque')->name('file.log');

resources/views/layouts/app.blade.php
<!DOCTYPE html>
<html lang="{{ config('app.locale') }}">
<head>
    @include('layouts.head')


</head>

<body>
    @include('layouts.preloader')

    <div id="wrapper">
        @include('layouts.header')

        @include('layouts.leftSidebar')
        <!-- Page Content -->
        <div id="page-wrapper">
            <div class="container-fluid">

                @include('layouts.title')

                @if(Session::has('flash_message'))
                    <div class="row">
                        <div class="col-md-12">
                            <div class="alert alert-success"><em> {!! session('flash_message') !!}</em>
                            </div>
                        </div>
                    </div>
                @endif
                <div class="row">
                    <div class="col-md-12">
                        @include ('errors.list') {{-- Including error file --}}
                    </div>
                </div>

                @yield('content')

                @include('layouts.rightSidebar')
            </div>
            <!-- /.container-fluid -->
            @include('layouts.footer')
        </div>
        <!-- /#page-wrapper -->
    </div>
    <!-- /#wrapper -->
    @include('layouts.script')
    <!-- Custom Theme JavaScript -->
    @yield('scripts')
</body>
</html>

resources/views/layouts/appError.blade.php
<!DOCTYPE html>
<html lang="{{ config('app.locale') }}">
<head>
    @include('layouts.head')


</head>

<body>
    @include('layouts.preloader')

    <div id="wrapper" class="error-page">

        @yield('content')


    </div>
    <!-- /#wrapper -->
    @include('layouts.script')
    <!-- Custom Theme JavaScript -->
    @yield('scripts')
</body>
</html>

resources/views/layouts/appLogin.blade.php
<!DOCTYPE html>
<html lang="{{ config('app.locale') }}">
<head>
    @include('layouts.head')

    @yield('style')
</head>

<body>
    @include('layouts.preloader')

    <div id="wrapper" class="login-register">
        <!-- Page Content -->
        <div class="login-box">
            @yield('content')

        </div>
        <!-- /#login-box -->
    </div>
    <!-- /#wrapper -->
    @include('layouts.script')
    <!-- Custom Theme JavaScript -->
    @yield('scripts')
</body>
</html>

resources/views/layouts/breadcrumbs.blade.php
@if (request()->route()->getName() == 'users.edit')

    {!! Breadcrumbs::render('users.edit', $user) !!}

@else

    @if (request()->route()->getName() == 'roles.edit')

        {!! Breadcrumbs::render('roles.edit', $role) !!}

    @else

        @if (request()->route()->getName() == 'permissions.edit')

            {!! Breadcrumbs::render('permissions.edit', $permission) !!}

        @else

            @if (request()->route()->getName() == 'articles.edit')

                {!! Breadcrumbs::render('articles.edit', $article) !!}

            @else

                {!! Breadcrumbs::render() !!}

            @endif

        @endif

    @endif

@endif

resources/views/layouts/footer.blade.php
<footer class="footer text-center"> 2017 &copy; boraplast. created by digipanda.net </footer>

resources/views/layouts/head.blade.php
<meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <meta name="description" content="">
    <meta name="author" content="">
    <link rel="icon" type="image/png" sizes="16x16" href="{{ asset('backend/plugins/images/favicon.png') }}">

    <!-- CSRF Token -->
    <meta name="csrf-token" content="{{ csrf_token() }}">

    <title>{{ config('app.name', 'Panda CMS') }} - @yield('title')</title>

    <!-- Bootstrap Core CSS -->
    <link href="{{ asset('backend/eliteadmin/bootstrap/dist/css/bootstrap.min.css') }}" rel="stylesheet">
    <link href="{{ asset('backend/plugins/bower_components/bootstrap-extension/css/bootstrap-extension.css') }}" rel="stylesheet">
    <!-- Menu CSS -->
    <link href="{{ asset('backend/plugins/bower_components/sidebar-nav/dist/sidebar-nav.min.css') }}" rel="stylesheet">
    <!-- morris CSS -->
    <link href="{{ asset('backend/plugins/bower_components/morrisjs/morris.css') }}" rel="stylesheet">
    <!-- animation CSS -->
    <link href="{{ asset('backend/eliteadmin/css/animate.css') }}" rel="stylesheet">

    @yield('style')

    <!-- Custom CSS -->
    <link href="{{ asset('backend/eliteadmin/css/style.css') }}" rel="stylesheet">
    <link href="{{ asset('css/styles.css') }}" rel="stylesheet">

    <!-- color CSS -->
    <link href="{{ asset('backend/eliteadmin/css/colors/default.css') }}" id="theme" rel="stylesheet">
    <!-- HTML5 Shim and Respond.js IE8 support of HTML5 elements and media queries -->
    <!-- WARNING: Respond.js doesn't work if you view the page via file:// -->
    <!--[if lt IE 9]>
    <script src="https://oss.maxcdn.com/libs/html5shiv/3.7.0/html5shiv.js"></script>
    <script src="https://oss.maxcdn.com/libs/respond.js/1.4.2/respond.min.js"></script>
    <![endif]-->

resources/views/layouts/header.blade.php
    <!-- Navigation -->
        <nav class="navbar navbar-default navbar-static-top m-b-0">
            <div class="navbar-header"> <a class="navbar-toggle hidden-sm hidden-md hidden-lg " href="javascript:void(0)" data-toggle="collapse" data-target=".navbar-collapse"><i class="ti-menu"></i></a>
                <div class="top-left-part">
                    <a class="logo" href="{{ route('dashboard') }}">
                        <b><img src="{{ asset('backend/plugins/images/eliteadmin-logo-dark.png') }}" alt="home" /></b>
                        <span class="hidden-xs"><img src="{{ asset('backend/plugins/images/eliteadmin-text-dark.png') }}" alt="home" /></span>
                    </a>
                </div>
                <ul class="nav navbar-top-links navbar-left hidden-xs">
                    <li><a href="javascript:void(0)" class="open-close hidden-xs waves-effect waves-light"><i class="icon-arrow-left-circle ti-menu"></i></a></li>

                    {{--
                    <li>
                        <form role="search" class="app-search hidden-xs">
                            <input type="text" placeholder="Search..." class="form-control">
                            <a href=""><i class="fa fa-search"></i></a>
                        </form>
                    </li>
                    --}}
                </ul>
                <ul class="nav navbar-top-links navbar-right pull-right">
                    <li class="right-side-toggle">
                        @if(Auth::user()->logo_societe != null)
                            <img src="{{ asset(Auth::user()->logo_societe) }}" />
                        @endif
                    </li>

                    <!-- /.dropdown -->
                </ul>
            </div>
            <!-- /.navbar-header -->
            <!-- /.navbar-top-links -->
            <!-- /.navbar-static-side -->
        </nav>

resources/views/layouts/leftSidebar.blade.php
    <!-- Left navbar-header -->
        <div class="navbar-default sidebar" role="navigation">
            <div class="sidebar-nav navbar-collapse slimscrollsidebar">

                <ul class="nav" id="side-menu">
                    <li> <a href="{{ route('dashboard.display') }}" class="waves-effect"><i data-icon="P" class="linea-icon linea-basic fa-fw"></i> <span class="hide-menu">Tableaux de bord</span></a> </li>

                    @hasrole('Admin')

                    <li> <a href="#" class="waves-effect"><i class="icon-people fa-fw"></i> <span class="hide-menu"> Les utilisateurs <span class="fa arrow"></span></span></a>

                        <ul class="nav nav-second-level">
                            <li> <a href="{{ route('users.index') }}">Tous les utilisateurs</a> </li>
                            <li> <a href="{{ route('users.create') }}">Ajouter un utilisateur</a> </li>
                        </ul>
                    </li>

                    <li> <a href="{{ route('roles.index') }}" class="waves-effect"><i class="icon-key fa-fw"></i> <span class="hide-menu">Roles</span></a> </li>
                    <li> <a href="{{ route('permissions.index') }}" class="waves-effect"><i class="icon-key fa-fw"></i> <span class="hide-menu">Autorisations</span></a> </li>

                    <li> <a href="#" class="waves-effect"><i class="icon-people fa-fw"></i> <span class="hide-menu"> Les articles <span class="fa arrow"></span></span></a>

                        <ul class="nav nav-second-level">
                            <li> <a href="{{ route('articles.index') }}">Tous les articles</a> </li>
                            <li> <a href="{{ route('articles.create') }}">Ajouter un article</a> </li>
                        </ul>
                    </li>

                    @else

                        @widget('nombreMois')

                        @widget('nombreSemaines')



                    @endhasrole



                    <li><a href="{{ route('logout') }}" class="waves-effect" onclick="event.preventDefault();
                                                     document.getElementById('logout-form').submit();"><i class="icon-logout fa-fw"></i> <span class="hide-menu">Déconnexion</span></a></li>
                    <form id="logout-form" action="{{ route('logout') }}" method="POST" style="display: none;">
                        {{ csrf_field() }}
                    </form>

                </ul>
            </div>
        </div>
        <!-- Left navbar-header end -->

resources/views/layouts/preloader.blade.php
<!-- Preloader -->
    <div class="preloader">
        <div class="cssload-speeding-wheel"></div>
    </div>

resources/views/layouts/rightSidebar.blade.php
{{--
<!-- .right-sidebar -->
<div class="right-sidebar">
    <div class="slimscrollright">
        <div class="rpanel-title"> Service Panel <span><i class="ti-close right-side-toggle"></i></span> </div>
        <div class="r-panel-body">
            <ul class="m-t-20 chatonline">
                <li><b>Chat option</b></li>
                <li>
                    <a href="javascript:void(0)"><img src="{{ asset('backend/plugins/images/users/varun.jpg') }}" alt="user-img" class="img-circle"> <span>Varun Dhavan <small class="text-success">online</small></span></a>
                </li>
                <li>
                    <a href="javascript:void(0)"><img src="{{ asset('backend/plugins/images/users/genu.jpg') }}" alt="user-img" class="img-circle"> <span>Genelia Deshmukh <small class="text-warning">Away</small></span></a>
                </li>
                <li>
                    <a href="javascript:void(0)"><img src="{{ asset('backend/plugins/images/users/ritesh.jpg') }}" alt="user-img" class="img-circle"> <span>Ritesh Deshmukh <small class="text-danger">Busy</small></span></a>
                </li>
                <li>
                    <a href="javascript:void(0)"><img src="{{ asset('backend/plugins/images/users/arijit.jpg') }}" alt="user-img" class="img-circle"> <span>Arijit Sinh <small class="text-muted">Offline</small></span></a>
                </li>
                <li>
                    <a href="javascript:void(0)"><img src="{{ asset('backend/plugins/images/users/govinda.jpg') }}" alt="user-img" class="img-circle"> <span>Govinda Star <small class="text-success">online</small></span></a>
                </li>
                <li>
                    <a href="javascript:void(0)"><img src="{{ asset('backend/plugins/images/users/hritik.jpg') }}" alt="user-img" class="img-circle"> <span>John Abraham<small class="text-success">online</small></span></a>
                </li>
                <li>
                    <a href="javascript:void(0)"><img src="{{ asset('backend/plugins/images/users/john.jpg') }}" alt="user-img" class="img-circle"> <span>Hritik Roshan<small class="text-success">online</small></span></a>
                </li>
                <li>
                    <a href="javascript:void(0)"><img src="{{ asset('backend/plugins/images/users/pawandeep.jpg') }}" alt="user-img" class="img-circle"> <span>Pwandeep rajan <small class="text-success">online</small></span></a>
                </li>
            </ul>
        </div>
    </div>
</div>
<!-- /.right-sidebar -->
--}}

resources/views/layouts/script.blade.php
<!-- jQuery -->
    <script src="{{ asset('backend/plugins/bower_components/jquery/dist/jquery.min.js') }}"></script>
    <!-- Bootstrap Core JavaScript -->
    <script src="{{ asset('backend/eliteadmin/bootstrap/dist/js/tether.min.js') }}"></script>
    <script src="{{ asset('backend/eliteadmin/bootstrap/dist/js/bootstrap.min.js') }}"></script>
    <script src="{{ asset('backend/plugins/bower_components/bootstrap-extension/js/bootstrap-extension.min.js') }}"></script>
    <!-- Menu Plugin JavaScript -->
    <script src="{{ asset('backend/plugins/bower_components/sidebar-nav/dist/sidebar-nav.min.js') }}"></script>
    <!--Counter js -->
    <script src="{{ asset('backend/plugins/bower_components/waypoints/lib/jquery.waypoints.js') }}"></script>
    <script src="{{ asset('backend/plugins/bower_components/counterup/jquery.counterup.min.js') }}"></script>
    <!--slimscroll JavaScript -->
    <script src="{{ asset('backend/eliteadmin/js/jquery.slimscroll.js') }}"></script>
    <!--Wave Effects -->
    <script src="{{ asset('backend/eliteadmin/js/waves.js') }}"></script>
    <!--Morris JavaScript -->
    <script src="{{ asset('backend/plugins/bower_components/raphael/raphael-min.js') }}"></script>
    <script src="{{ asset('backend/plugins/bower_components/morrisjs/morris.js') }}"></script>
    <script src="{{ asset('backend/plugins/bower_components/jquery-sparkline/jquery.sparkline.min.js') }}"></script>

resources/views/layouts/title.blade.php
<div class="row bg-title">
    <div class="col-lg-6 col-md-6 col-sm-12 col-xs-12">
        <h4 class="page-title">@yield('title')</h4>
    </div>
    <div class="col-lg-6 col-sm-6 col-md-12 col-xs-12">
        @include('layouts.breadcrumbs')
    </div>
    <!-- /.col-lg-12 -->
</div>