routes/web.php
<?php

Auth::routes();


Route::get('/', 'HomeController@commande')->name('dashboard');

Route::get('/dashboard', 'HomeController@commande')->name('dashboard.display');


Route::resource('users', 'UserController');

Route::match(['put', 'patch'],'users/changePass/{user}', 'UserController@updatePass')->name('users.updatePass');
Route::match(['put', 'patch'],'users/changeLogo/{user}', 'UserController@updateLogo')->name('users.updateLogo');


Route::resource('roles', 'RoleController');

Route::resource('permissions', 'PermissionController');

Route::resource('posts', 'PostController');

Route::resource('articles', 'ArticleController');


Route::get('/commandes/{nombre_semaine?}/{nombre_anne?}', 'CommandesController@semaine')->name('commandes');
Route::get('/commandes-historique/{nombre_semaine?}', 'CommandesController@historiqueSemaine')->name('historique.commandes');
Route::post('/commande/create', 'CommandesController@store')->name('commande.create');
Route::post('/commande/create2', 'CommandesController@store2')->name('commande.create2');

Route::get('/previsions/{anne?}/{nombre_mois?}', 'PrevisionsController@mois')->name('previsions');
Route::post('/previsions/create', 'PrevisionsController@store')->name('previsions.create');

Route::get('/previsions_hebdo/{anne?}/{nombre_mois?}', 'PrevisionsController@mois2')->name('previsions_hebdo');
Route::post('/previsions/create2', 'PrevisionsController@store2')->name('previsions.create2');

Route::post('/previsions/save_repartition', 'PrevisionsController@saveRepartition')->name('repartition.save');

/*** For ERP **/
Route::get('/getcommandes/{last_update}', 'ErpController@getCommandes')->name('erp.commandes');
Route::get('/getprevisions/{last_update}', 'ErpController@getPrevisions')->name('erp.previsions');

Route::get('/historique-log/{id_user?}', 'LogsController@getHistorque')->name('file.log');

app/Article.php
<?php

namespace App;

use Illuminate\Database\Eloquent\Model;

class Article extends Model
{
    protected $table = 'articles';

    protected $fillable = [
        'reference', 'designation', 'unite'
    ];


    public function articlesActuels()
    {
        return $this->hasMany('\App\ArticlesActuels', 'article_id');
    }

    public function commandes()
    {
        return $this->hasMany('\App\Commande', 'article_id');
    }

    public function previsions()
    {
        return $this->hasMany('\App\Prevision', 'article_id');
    }

    public function previsionsc()
    {
        return $this->hasMany('\App\Previsionc', 'article_id');
    }
}

app/Http/Controllers/ArticleController.php
<?php

namespace App\Http\Controllers;

use Illuminate\Http\Request;

use App\Article;
use Auth;
use Session;

class ArticleController extends Controller
{
    public function __construct() {
        $this->middleware(['auth', 'clearance']);
    }

    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
        $articles = Article::orderby('reference', 'asc')->paginate(100); //show only 5 items at a time in descending order

        return view('articles.index', compact('articles'));
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        return view('articles.create');
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request)
    {
        //Validating title and body field
        $this->validate($request, [
            'reference'=>'required|max:100',
            'designation' =>'required',
            'unite' =>'required',
        ]);


        $article = Article::create($request->only('reference', 'designation', 'unite'));

        //Display a successful message upon save
        return redirect()->route('articles.index')
            ->with('flash_message', 'Article,
             '. $article->reference.' bien ajouté');
    }

    /**
     * Display the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function show($id)
    {
        //
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function edit($id)
    {
        $article = Article::findOrFail($id);

        return view('articles.edit', compact('article'));
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, $id)
    {
        $this->validate($request, [
            'reference'=>'required|max:100',
            'designation' =>'required',
            'unite' =>'required',
        ]);

        $article = Article::findOrFail($id);
        $article->reference = $request->input('reference');
        $article->designation = $request->input('designation');
        $article->unite = $request->input('unite');
        $article->save();

        return redirect()->route('articles.index')->with('flash_message',
            'Article, '. $article->reference.' bien modifié');
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function destroy($id)
    {
        $article = Article::findOrFail($id);
        $article->delete();

        return redirect()->route('articles.index')
            ->with('flash_message',
                'Article bien supprimé');
    }
}

resources/views/articles/create.blade.php
@extends('layouts.app')

@section('title', 'Ajouter un article')

@section('content')

    <div class="row">
        <div class="col-lg-12">
            <div class="white-box">
                <h3 class="box-title"><i class='fa fa-shopping-cart'></i> Nouveau article</h3>

                {{ Form::open(array('route' => 'articles.store', 'class' => 'form-material form-horizontal m-t-30')) }}

                <div class="form-group">
                    {{ Form::label('reference', 'Référence') }}<br>
                    {{ Form::text('reference', null, array('class' => 'form-control')) }}
                </div>


                <div class="form-group">
                    {{ Form::label('designation', 'Designation') }}<br>
                    {{ Form::text('designation', null, array('class' => 'form-control')) }}
                </div>

                <div class="form-group">
                    {{ Form::label('unite', 'Unité') }}<br>
                    {{ Form::text('unite', null, array('class' => 'form-control')) }}
                </div>

                {{ Form::submit('Créer Article', array('class' => 'btn btn-success btn-lg btn-block')) }}

                {{ Form::close() }}

            </div>
        </div>
    </div>

@endsection

@section('scripts')
    <script src="{{ asset('backend/eliteadmin/js/custom.min.js') }}"></script>

    <script>
        $(document).ready(function() {


        });
    </script>

@endsection

resources/views/articles/edit.blade.php
@extends('layouts.app')

@section('title', "Modification Article")

@section('content')

    <div class="row">
        <div class="col-lg-12">
            <div class="white-box">
                <h3 class="box-title m-b-0"><i class='fa fa-shopping-cart'></i> Modifier l'article {{ $article->reference }} </h3>

                {{ Form::model($article, array('route' => array('articles.update', $article->id), 'method' => 'PUT', 'class' => 'form-material form-horizontal m-t-30')) }}

                <div class="form-group">
                    {{ Form::label('reference', 'Référence') }}<br>
                    {{ Form::text('reference', null, array('class' => 'form-control')) }}
                </div>


                <div class="form-group">
                    {{ Form::label('designation', 'Designation') }}<br>
                    {{ Form::text('designation', null, array('class' => 'form-control')) }}
                </div>

                <div class="form-group">
                    {{ Form::label('unite', 'Unité') }}<br>
                    {{ Form::text('unite', null, array('class' => 'form-control')) }}
                </div>

                {{ Form::submit('Modifer un article', array('class' => 'btn btn-primary')) }}

                {{ Form::close() }}

            </div>
        </div>
    </div>

@endsection

@section('scripts')
    <script src="{{ asset('backend/eliteadmin/js/custom.min.js') }}"></script>

    <script>
        $(document).ready(function() {


        });
    </script>

@endsection

resources/views/articles/index.blade.php
@extends('layouts.app')

@section('title', 'Tous les articles')

@section('content')
    <!-- .row -->
    <div class="row">
        <div class="col-sm-12">
            <div class="white-box">
                <h3 class="box-title"><i class="fa fa-shopping-cart"></i> Gestion des articles</h3>
                <div class="table-responsive">
                    <table class="table table-bordered table-striped">

                        <thead>
                        <tr>
                            <th>Référence</th>
                            <th>Designation</th>
                            <th>Unité</th>
                            <th>Date de création</th>
                            <th>Operations</th>
                        </tr>
                        </thead>

                        <tbody>
                        @foreach ($articles as $article)
                            <tr>

                                <td>{{ $article->reference }}</td>
                                <td>{{ $article->designation }}</td>
                                <td>{{ $article->unite }}</td>
                                <td>{{ $article->created_at->format('d/m/Y h:i') }}</td>

                                <td>
                                    <a href="{{ route('articles.edit', $article->id) }}" class="btn btn-info pull-left" style="margin-right: 3px;">Modifier</a>

                                    {!! Form::open(['method' => 'DELETE', 'route' => ['articles.destroy', $article->id] ]) !!}
                                    {!! Form::submit('Supprimer', ['class' => 'btn btn-danger']) !!}
                                    {!! Form::close() !!}

                                </td>
                            </tr>
                        @endforeach
                        </tbody>

                    </table>
                </div>
            </div>
        </div>
    </div>
@endsection

@section('scripts')
    <script src="{{ asset('backend/eliteadmin/js/custom.min.js') }}"></script>

    <script>
        $(document).ready(function() {


        });
    </script>

@endsection

resources/views/articles/show.blade.php
@extends('layouts.app')

@section('title', '| View Post')

@section('content')

    <div class="container">

        <h1>{{ $post->title }}</h1>
        <hr>
        <p class="lead">{{ $post->body }} </p>
        <hr>
        {!! Form::open(['method' => 'DELETE', 'route' => ['posts.destroy', $post->id] ]) !!}
        <a href="{{ url()->previous() }}" class="btn btn-primary">Back</a>
        @can('Edit Post')
            <a href="{{ route('posts.edit', $post->id) }}" class="btn btn-info" role="button">Edit</a>
        @endcan
        @can('Delete Post')
            {!! Form::submit('Delete', ['class' => 'btn btn-danger']) !!}
        @endcan
        {!! Form::close() !!}

    </div>

@endsection